dbt_bq_util:
  outputs:
    cli:
      dataset: "{{ var('DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      location: "{{ var('LOCATION') }}"
      priority: interactive
      project: "{{ var('PROJECT') }}"
      threads: 4
      type: bigquery
  target: cli
